<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>buduns_server.WebAPI</RootNamespace>
    <UserSecretsId>buduns-server-webapi</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Postgresql.Alternative" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\buduns-server.Application\buduns-server.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\buduns-server.Infrastructure\buduns-server.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\buduns-server.Persistence\buduns-server.Persistence.csproj" />
  </ItemGroup>

</Project>
