<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>buduns_server.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- SignInManager ve AddIdentity paylasilan framework'ten gelir. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\buduns-server.Application\buduns-server.Application.csproj" />
  </ItemGroup>

</Project>
